
### Teste GET
GET http://localhost:8080/healthy


###

### Teste GET
GET http://localhost:8080/categories


###

### Teste POST

POST  http://localhost:8080/categories
Content-Type: "application/json"

{
    "Name": "Docker"
}