### Teste GET
# Este é um exemplo de uma solicitação GET para obter dados de um recurso
GET http://localhost:8080/music
Accept: application/json

###
GET http://localhost:8080/music/1
Accept: application/json

### Teste POST
# Este é um exemplo de uma solicitação POST para criar um novo recurso
POST http://localhost:8080/music
Content-Type: application/json

{
  "titulo": "Have You Ever Seen The Rain?",
  "artista": "creedence clearwater revival",
  "album": "Pendulum",
  "lancamento": "1971",
  "genero": "Rock"
}

###

### Teste PUT
# Este é um exemplo de uma solicitação PUT para atualizar um recurso existente
PUT http://localhost:8080/music/1
Content-Type: application/json

{
  "nome": "Recurso Atualizado",
  "valor": 5678
}

###

### Teste DELETE
# Este é um exemplo de uma solicitação DELETE para remover um recurso
DELETE http://localhost:8080/music/5

###
