version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-meu_banco}
      MYSQL_USER: ${MYSQL_USER:-meu_usuario}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-minha_senha}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - setup-network

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER:-meu_usuario}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-minha_senha}
    depends_on:
      - db
    networks:
      - setup-network

volumes:
  db_data:

networks:
  setup-network:
